# theme = "Tokyonight_Night"

# [colors]
# author = "Folke"
# name = "TokyoNight Night"

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x15161E"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM = "alacritty"

[font]
size = 20.0

# <$>
# -> -->
# Sat Apr 05 15:02
[font.normal]
family = "victor mono nerd font"
style = "semibold"


# family = "sauce code pro mono nerd font"

[font.bold]
family = "Victor Mono Nerd Font"
style = "Bold"

[font.italic]
family = "Victor Mono Nerd Font"
style = "Mono"

[font.bold_italic]
family = "Victor Mono Nerd Font"
style = "Bold"

[window]
padding = { x = 14, y = 7}
opacity = 0.75

